- hosts: localhost
  tasks:
    - name: Docker YUM
      yum:
        name: 
          - docker
          - python3-pip
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Node.js Docker image
      community.docker.docker_image:
        name: "honeycanad21/cicdtermproject:latest"
        source: pull
        
    - name: Create Node.js Docker container
      community.docker.docker_container:
        name: cicdtermproject
        image: "honeycanad21/cicdtermproject:latest"
        state: started
        ports:
          - "3000:3000"
