
- hosts: localhost
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Python
      apt:
        name: python
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Pull Node.js app from Docker Hub
      docker_image:
        name: honeycanada21/cicdtermproject
        source: pull

    - name: Run Node.js app
      docker_container:
        name: nodejs_app
        image: honeycanada21/cicdtermproject
        state: started
        published_ports: 3000:3000

