---
- hosts: localhost
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Python requests library
      pip:
        name: requests
        state: present

    - name: Install Docker using official script
      shell: curl -fsSL https://get.docker.com | sh

    - name: Start Docker service
      systemd:
        name: docker
        state: started

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Login to Docker Hub
      docker_login:
        username: honeycanada21
        password: Psswd@docker1

    - name: Build Docker image
      docker_image:
        name: honeycanad21/cicdtermproject
        source: build
        build:
          path: ./

    - name: Push Docker image to Docker Hub
      docker_image:
        name: honeycanad21/cicdtermproject
        source: push

    - name: Pull Node.js app from Docker Hub
      docker_image:
        name: honeycanad21/cicdtermproject
        source: pull

    - name: Run Node.js app
      docker_container:
        name: nodejs_app
        image: honeycanad21/cicdtermproject
        state: started
        published_ports: 3000:3000
