
- hosts: localhost
  become: yes
  tasks:
   

    - name: Pull Node.js app from Docker Hub
      docker_image:
        name: "honeycanad21/cicdtermproject:latest"
        source: pull

    - name: Run Node.js app
      docker_container:
        name: nodejs_app
        image: "honeycanad21/cicdtermproject:latest"
        state: started
        published_ports: 3000:3000
