
- name: Install Python, Ansible, and Docker, then Deploy Node.js App from Docker
  hosts: localhost
  gather_facts: false  # We don't gather facts for localhost

  tasks:
    - name: Install Python (if not present)
      become: true
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-is-python3)

    - name: Install Ansible (if not present)
      become: true
      raw: test -e /usr/bin/ansible || (apt -y update && apt install -y ansible)

    - name: Set LD_LIBRARY_PATH
        run: export LD_LIBRARY_PATH=/path/to/lib:/home/c0870558/actions-runner/_work/_tool/Python/3.12.0/x64/lib/libpython3.12.so.1.0

    - name: Install Docker (if not present)
      become: true
      raw: test -e /usr/bin/docker || (apt -y update && apt install -y docker.io)

    - name: Start Docker Service
      become: true
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Node.js Docker image
      become: true
      docker_image:
        name: node:latest

    - name: Run Node.js Docker container
      become: true
      docker_container:
        name: nodejs_app_container
        image: node:latest
        ports:
          - "3000:3000"
        detach: yes
