
- hosts: localhost
  become: yes
  tasks:
    - name: Install Python
      apt:
        name: python
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Login to Docker Hub
      docker_login:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Node.js app from Docker Hub
      docker_image:
        name: honeycanad21/cicdtermproject
        source: pull

    - name: Run Node.js app
      docker_container:
        name: nodejs_app
        image: honeycanad21/cicdtermproject
        state: started
        published_ports: 3000:3000

