name: deploy application to testing env

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    # - '.github/workflows/ecommerceapi-AutoDeployTrigger-ed505b62-30ed-4a26-84ad-a137e1bbec40.yml'

  # Allow manual trigger 
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Use custom action to checkout branch
        uses: honeymakhija/cicd_termproject@main
        with:
          branch: "main"
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

          
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: honeycanada21/cicdtermproject:${{ github.sha }}
          file: ./Dockerfile
          context: ./


      - name: Run tests
        run: |
          npm test

      - name: Write test results to file
        run: |
         if [ $? -eq 0 ]; then
          echo "All tests passed" > test_file.txt
          else
          echo "Tests failed" > test_file.txt
           fi

      - name: Archive test results
        uses: honeymakhija/cicd_termproject@main
        with:
          branch: "main"


         
       

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.ECOMMERCEAPI_AZURE_CREDENTIALS }}

      # - name: Build and push container image to registry
      #   uses: azure/container-apps-deploy-action@v2
      #   with:
      #     appSourcePath: ${{ github.workspace }} 
      #     registryUrl: docker.io
      #     registryUsername: ${{ secrets.ECOMMERCEAPI_REGISTRY_USERNAME }}
      #     registryPassword: ${{ secrets.ECOMMERCEAPI_REGISTRY_PASSWORD }}
      #     containerAppName: ecommerceapi
      #     resourceGroup: rgecommerce
      #     imageToBuild: rahulkumar2620/ecommerceapi:${{ github.sha }}
      #     dockerfilePath: Dockerfile

     

