name: deploy application to testing env

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    # - '.github/workflows/ecommerceapi-AutoDeployTrigger-ed505b62-30ed-4a26-84ad-a137e1bbec40.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test > results.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results.txt

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.ECOMMERCEAPI_AZURE_CREDENTIALS }}

      # - name: Build and push container image to registry
      #   uses: azure/container-apps-deploy-action@v2
      #   with:
      #     appSourcePath: ${{ github.workspace }} 
      #     registryUrl: docker.io
      #     registryUsername: ${{ secrets.ECOMMERCEAPI_REGISTRY_USERNAME }}
      #     registryPassword: ${{ secrets.ECOMMERCEAPI_REGISTRY_PASSWORD }}
      #     containerAppName: ecommerceapi
      #     resourceGroup: rgecommerce
      #     imageToBuild: rahulkumar2620/ecommerceapi:${{ github.sha }}
      #     dockerfilePath: Dockerfile

     

