name: Run Ansible Playbook

on:
  push:
    branches: 
      - main
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

          
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: honeycanada21/cicdtermproject:${{ github.sha }}
          file: ./Dockerfile
          context: ./   

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Set LD_LIBRARY_PATH
        run: echo "LD_LIBRARY_PATH=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')" >> $GITHUB_ENV

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook ansible-playbook.yml
